

### ---- ITEMS ----
### get all items
GET https://markkinapaikka.onrender.com/api/items HTTP/1.1

### get item by id
GET https://markkinapaikka.onrender.com/api/items/3 HTTP/1.1

### post new item
POST https://markkinapaikka.onrender.com/api/items HTTP/1.1
Authorization: BEARER {{authToken}}
content-type: application/json

{
    "user_id": 3,
    "title": "Jäkki",
    "description": "Priima istuttava jakkara",
    "price": 99,
    "category": "Kalusteet",
    "location": "Pirkanmaa",
    "image_url": "asdsadasdasd"
}

### update item

# not applied in client hence anyone can update and delete items
PUT https://markkinapaikka.onrender.com/api/items/2 HTTP/1.1
Authorization: BEARER {{authToken}}
content-type: application/json

{
    "title": "Moottorisaha Stihl",
    "description": "Uudenveroinen",
    "price": 59.50,
    "category": "Työkalut",
    "location": "Pirkanmaa",
    "image_url": "urlkuvaan;D"
}

### delete item by id
DELETE  https://markkinapaikka.onrender.com/api/items/2 HTTP/1.1
Authorization: BEARER {{authToken}}


### ---- USERS ----

### get user by id
GET https://markkinapaikka.onrender.com/api/users/8 HTTP/1.1

### SIGN UP USER
POST https://markkinapaikka.onrender.com/api/users/signup HTTP/1.1
content-type: application/json

{
    "email": "tommi",
    "name": "Sane", 
    "password": "123",
    "phone": "0401234567"
}

### LOGIN USER
# @name login
POST https://markkinapaikka.onrender.com/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "tommi",
    "password": "123"
}

###
@authToken = {{login.response.body.token}}