-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 17:59:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema markkinapaikka_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema markkinapaikka_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `markkinapaikka_db` DEFAULT CHARACTER SET utf8 ;
USE `markkinapaikka_db` ;

-- -----------------------------------------------------
-- Table `markkinapaikka_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markkinapaikka_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `prefered_contact` VARCHAR(45) NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markkinapaikka_db`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markkinapaikka_db`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `price` FLOAT NOT NULL,
  `category` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `image_url` VARCHAR(255) NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_items_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `markkinapaikka_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markkinapaikka_db`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markkinapaikka_db`.`favorites` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorites_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_favorites_items1_idx` (`items_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `markkinapaikka_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `markkinapaikka_db`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Sample data for tables
-- -----------------------------------------------------
INSERT INTO `users` (`email`, `password`, `fname`, `lname`, `phone`, `prefered_contact`, `date_created`, `date_modified`)
VALUES
('user1@example.com', 'password1', 'John', 'Doe', '123456789', 'email', NOW(), NOW()),
('user2@example.com', 'password2', 'Jane', 'Smith', '987654321', 'phone', NOW(), NOW()),
('user3@example.com', 'password3', 'Alice', 'Johnson', '555555555', 'phone', NOW(), NOW());

-- Sample data for `items` table
INSERT INTO `items` (`user_id`, `title`, `description`, `price`, `category`, `location`, `image_url`, `date_created`, `date_updated`)
VALUES
(1, 'Item 1', 'Description for item 1', 50.00, 'Category 1', 'Location 1', 'https://example.com/image1.jpg', NOW(), NOW()),
(2, 'Item 2', 'Description for item 2', 75.00, 'Category 2', 'Location 2', 'https://example.com/image2.jpg', NOW(), NOW()),
(3, 'Item 3', 'Description for item 3', 100.00, 'Category 3', 'Location 3', 'https://example.com/image3.jpg', NOW(), NOW());

-- Sample data for `favorites` table
INSERT INTO `favorites` (`id`, `users_id`, `items_id`)
VALUES
(1, 1, 2),
(2, 2, 1),
(3, 3, 3);