-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 17:59:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema freedb_markkinapaikka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freedb_markkinapaikka` DEFAULT CHARACTER SET utf8 ;

USE `freedb_markkinapaikka` ;

-- -----------------------------------------------------
-- Table `freedb_markkinapaikka`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedb_markkinapaikka`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `prefered_contact` VARCHAR(45) NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedb_markkinapaikka`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedb_markkinapaikka`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `price` FLOAT NOT NULL,
  `category` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `image_url` VARCHAR(255) NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_items_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `freedb_markkinapaikka`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedb_markkinapaikka`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedb_markkinapaikka`.`favorites` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorites_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_favorites_items1_idx` (`items_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `freedb_markkinapaikka`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `freedb_markkinapaikka`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
