-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 17:59:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema markkinapaikka_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `markkinapaikka_db` DEFAULT CHARACTER SET utf8 ;

USE `markkinapaikka_db` ;

-- -----------------------------------------------------
-- Table `markkinapaikka_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markkinapaikka_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `prefered_contact` VARCHAR(45) NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markkinapaikka_db`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markkinapaikka_db`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `price` FLOAT NOT NULL,
  `category` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `image_url` VARCHAR(255) NULL,
  `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_items_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `markkinapaikka_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `markkinapaikka_db`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markkinapaikka_db`.`favorites` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorites_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_favorites_items1_idx` (`items_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `markkinapaikka_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `markkinapaikka_db`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Sample data for users table
INSERT INTO `markkinapaikka_db`.`users` (`email`, `password`, `fname`, `lname`, `phone`, `prefered_contact`) VALUES
('john@example.com', 'password123', 'John', 'Doe', '+123456789', 'email'),
('jane@example.com', 'securepass', 'Jane', 'Smith', '+987654321', 'phone');

-- Sample data for items table
INSERT INTO `markkinapaikka_db`.`items` (`user_id`, `title`, `description`, `price`, `category`, `location`, `image_url`) VALUES
(1, 'Bicycle', 'Gently used bicycle in good condition', 150.00, 'Sports & Outdoors', 'New York', 'https://example.com/bicycle.jpg'),
(2, 'Smartphone', 'Brand new smartphone with latest features', 600.00, 'Electronics', 'Los Angeles', 'https://example.com/smartphone.jpg');

-- Sample data for favorites table
INSERT INTO `markkinapaikka_db`.`favorites` (`users_id`, `items_id`) VALUES
(1, 2),
(2, 1);

-- favorites wont generate here, because user id doesnt exist yet, it generates automatically