name: CI/CD

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verification:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetch code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
            node-version: "18"
          
      - name: install server deps
        working-directory: ./server
        run: npm ci

      # run docker before tests  
      #- name: run tests on server
      #  working-directory: ./server
      #  run: npm run test

      - name: run linter on server
        working-directory: ./server
        run: npm run lint

        # install deps
        # run linter
        # run tests
        # run build
        # start sql
        # on server and client
