name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verification:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetch code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
            node-version: "18"

        # install deps
        # run linter
        # run tests
        # run build
        # start sql
        # on server and client
