name: CI/CD

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verification:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetch code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
            node-version: "18"
          
      - name: install server deps
        working-directory: ./server
        run: npm ci

      #- name: run tests on server
      #  working-directory: ./server
      #  run: npm run test

      - name: run linter on server
        working-directory: ./server
        run: npm run lint

      - name: install client deps
        working-directory: ./client
        run: npm ci

      - name: run linter on client
        working-directory: ./client
        run: npm run lint

      #- name: Build the client
      #  working-directory: ./client
      #  run: npm run build

        # install deps
        # run linter
        # run tests
        # run build
        # start sql
        # on server and client

  build-and-push-image:
    needs: ["verification"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
